package seeder

import (
	"bytes"
	"fmt"
	"strings"
)

// generateConsentPDF creates a minimal single-page PDF with the consent title
// and agreement checkbox texts. The PDF uses built-in Helvetica fonts and
// requires no external Go dependencies.
//
// The generated PDF is a well-formed PDF-1.4 document that react-pdf (pdf.js)
// can parse and render successfully — this is required because the consent MFE's
// SignView gates the viewConsent() lifecycle RPC on pdfLoaded, which only fires
// after the PDF finishes rendering.
func generateConsentPDF(title string, checkboxTexts []string) []byte {
	// Build the content stream (PDF text-drawing operators).
	var cs bytes.Buffer
	cs.WriteString("BT\n")

	// Title in Helvetica-Bold 18pt
	cs.WriteString("/F2 18 Tf\n")
	cs.WriteString("72 720 Td\n")
	cs.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDF(title)))

	// Horizontal rule (draw a line in the graphics state)
	cs.WriteString("ET\n")
	cs.WriteString("0.8 0.8 0.8 RG\n") // light grey
	cs.WriteString("72 706 468 0.5 re f\n")
	cs.WriteString("BT\n")

	// Subtitle in Helvetica 11pt
	cs.WriteString("/F1 11 Tf\n")
	cs.WriteString("72 686 Td\n")
	cs.WriteString("(By signing this document, you agree to the following:) Tj\n")

	// Each checkbox text, indented with a bullet marker
	for _, text := range checkboxTexts {
		cs.WriteString("0 -28 Td\n")
		lines := wrapPDFText(text, 80)
		for i, line := range lines {
			if i > 0 {
				cs.WriteString("0 -14 Td\n")
			}
			prefix := "\\225 " // bullet character (•)
			if i > 0 {
				prefix = "   " // indent continuation lines
			}
			cs.WriteString(fmt.Sprintf("(%s%s) Tj\n", prefix, escapePDF(line)))
		}
	}

	// Footer
	cs.WriteString("0 -40 Td\n")
	cs.WriteString("/F1 9 Tf\n")
	cs.WriteString("(This document was generated by the standalone seeding tool.) Tj\n")
	cs.WriteString("ET\n")

	contentBytes := cs.Bytes()

	// Assemble the PDF objects. We track byte offsets for the xref table.
	var pdf bytes.Buffer
	offsets := make([]int, 0, 6)

	pdf.WriteString("%PDF-1.4\n")
	// Binary comment to signal this is a binary file (PDF spec recommendation)
	pdf.WriteString("%\xe2\xe3\xcf\xd3\n")

	// Object 1: Catalog
	offsets = append(offsets, pdf.Len())
	pdf.WriteString("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

	// Object 2: Pages
	offsets = append(offsets, pdf.Len())
	pdf.WriteString("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")

	// Object 3: Page (US Letter, 612x792 points)
	offsets = append(offsets, pdf.Len())
	pdf.WriteString("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]")
	pdf.WriteString(" /Contents 4 0 R")
	pdf.WriteString(" /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >>")
	pdf.WriteString(" >>\nendobj\n")

	// Object 4: Content stream
	offsets = append(offsets, pdf.Len())
	pdf.WriteString(fmt.Sprintf("4 0 obj\n<< /Length %d >>\nstream\n", len(contentBytes)))
	pdf.Write(contentBytes)
	pdf.WriteString("\nendstream\nendobj\n")

	// Object 5: Font — Helvetica (regular)
	offsets = append(offsets, pdf.Len())
	pdf.WriteString("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n")

	// Object 6: Font — Helvetica-Bold
	offsets = append(offsets, pdf.Len())
	pdf.WriteString("6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n")

	// Cross-reference table
	xrefOffset := pdf.Len()
	numObjs := len(offsets) + 1 // +1 for the free entry (object 0)
	pdf.WriteString("xref\n")
	pdf.WriteString(fmt.Sprintf("0 %d\n", numObjs))
	pdf.WriteString("0000000000 65535 f \n") // object 0 is always free
	for _, off := range offsets {
		pdf.WriteString(fmt.Sprintf("%010d 00000 n \n", off))
	}

	// Trailer
	pdf.WriteString("trailer\n")
	pdf.WriteString(fmt.Sprintf("<< /Size %d /Root 1 0 R >>\n", numObjs))
	pdf.WriteString("startxref\n")
	pdf.WriteString(fmt.Sprintf("%d\n", xrefOffset))
	pdf.WriteString("%%EOF\n")

	return pdf.Bytes()
}

// escapePDF escapes special characters for a PDF string literal.
func escapePDF(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "(", "\\(")
	s = strings.ReplaceAll(s, ")", "\\)")
	return s
}

// wrapPDFText performs simple word-wrapping at maxChars characters.
func wrapPDFText(s string, maxChars int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{""}
	}
	var lines []string
	current := words[0]
	for _, word := range words[1:] {
		if len(current)+1+len(word) > maxChars {
			lines = append(lines, current)
			current = word
		} else {
			current += " " + word
		}
	}
	lines = append(lines, current)
	return lines
}
