# Used only for initial provisioning.
services:
  browser:
    build:
      context: ../browser-common
      args:
        APP_ORIGIN: "application-server:8888"
  app:
    image: workbench-virtual-browser:jupyterlab
    build:
      context: .
      additional_contexts:
        jupyter-extension-builder: service:jupyter-common-extension-builder
