services:
  app:
    container_name: "application-server"
    build:
      context: .
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - 8080:8080
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      AURORA_RESOURCE_ID: "${AURORA_RESOURCE_ID:-}"

networks:
  app-network:
    external: true
