version: "2.4"
services:
  app:
    container_name: "application-server"
    image: "arfodublo/cursor-in-browser:1.7.52-x64"
    restart: always
    volumes:
      - .:/workspace:cached
      - cursor-data:/cursor
      - cursor-config:/config
    ports:
      - "8080:8080"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
volumes:
  cursor-data:
  cursor-config:
