include:
  - ../aou-common/aou-common-compose.yaml
services:
  app:
    container_name: "application-server"
    shm_size: "${templateOption:shmSize}"
    mem_limit: "${templateOption:memoryLimit}"
    build:
      context: ../workbench-jupyter-parabricks
      additional_contexts:
        extension-builder: service:aou-common-extension-builder
        load-envs: service:aou-common-load-envs
      target: parabricks-aou
    user: jupyter
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--LabApp.token=''"]
  wondershaper:
    container_name: "wondershaper"
    image: "us-west2-docker.pkg.dev/shared-pub-buckets-94mvrf/workbench-artifacts/app-wondershaper@sha256:dc84f6ca005cbda3c2df529371dda84deee05d5ddced3e2497ca9e1edcc109f1"
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
networks:
  app-network:
    external: true
