version: "2.4"
services:
  app:
    container_name: "application-server"
    image: nvcr.io/nvidia/rapidsai/notebooks:25.08-cuda12.9-py3.13
    restart: always
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: ["/home/rapids/entrypoint.sh"]
    command: python -m jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/workspace
networks:
  app-network:
    external: true
