version: "2.4"
services:
  app:
    container_name: "application-server"
    build:
      context: .
      dockerfile: Dockerfile
    user: "abc:${DOCKER_GID}"
    restart: always
    volumes:
      - .:/workspace:cached
      - work:/config:cached
      # mount Host machine's docker.sock to container's docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      # mount Host machine's /etc/group to container's /etc/host-group
      - /etc/group:/etc/host-group
      # mount Host machine's default docker config dir to container's abc user docker config dir
      - /etc/docker:/config/.docker
    ports:
      - "8443:8443"
    environment:
      USER: "abc"
      DEFAULT_WORKSPACE: "/config"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
volumes:
  work:
