version: "2.4"
services:
  app:
    container_name: "application-server"
    image: "nvcr.io/nvidia/clara/clara-parabricks:4.5.1-1"
    user: root
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: tail -f /dev/null # This keeps the container alive
networks:
  app-network:
    external: true