# Use official Python image
FROM nvcr.io/nvidia/nemo:24.09

# Set working directory
# WORKDIR /workspace

# Install NeMo and JupyterLab
# RUN pip install --upgrade pip && \
#     pip install nemo_toolkit jupyterlab

# # Expose ports for JupyterLab and example NeMo service
# EXPOSE 8888
# EXPOSE 5000

# Start JupyterLab by default
# CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--LabApp.token=''"]
# Make sure python points to python3
# RUN sudo ln -s /usr/bin/python3 /usr/bin/python