name: 'Smoke test'
inputs:
  template:
    description: 'Template to test'
    required: true
  user:
    description: 'Username of container user'
    required: true
  workbench_tools:
    description: 'Whether to test workbench tools'
    required: true
  options:
    description: 'JSON string of additional options for building the app'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3

    - name: "Copy startup scripts"
      shell: bash
      run: |
        cp test/vm-metadata.sh startupscript/gcp/
        for dir in src/*/; do
          if [[ -d "${dir}" ]]; then
            cp -r startupscript "${dir}"
          fi
        done
    - name: Build template
      id: build_template
      shell: bash
      env:
        OPTIONS: ${{ inputs.options }}
      run: .github/actions/smoke-test/build.sh "${{ inputs.template }}" "$OPTIONS"

    - name: Test template
      id: test_template
      shell: bash
      run: .github/actions/smoke-test/test.sh "${{ inputs.template }}" "${{ inputs.user }}" "${{ inputs.workbench_tools }}"
