services:
  app:
    container_name: "application-server"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    ports:
      - 8000:8000
    networks:
      - app-network
    # SYS_ADMIN and fuse are required to mount workspace resources into the
    # container.
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

networks:
  app-network:
    external: true
