set.seed(189771)
frame <- data.frame(group=rep(1:100,1000), value=rnorm(100000))
result <- aggregate(value ~ group, frame, mean)
stopifnot(nrow(result) == 100, all(is.finite(result$value)))
output <- tempfile(fileext=".png")
png(output)
plot(result$group, result$value)
dev.off()
stopifnot(file.info(output)$size > 1000)
unlink(output)
cat("dependency-workload-ok\n")
