services:
  app:
    # The container name must be "application-server"
    container_name: "application-server"
    # This can be either a pre-existing image or built from a Dockerfile
    image: "jupyter/scipy-notebook:latest"
    # build:
    #   context: .
    restart: always
    user: "jovyan"
    volumes:
      - .:/workspace:cached
      - work:/home/jovyan/work
    # The port specified here will be forwarded and accessible from the
    # Workbench UI. Port 8888 is for JupyterLab, port 7860 is for Gradio apps
    ports:
      - 8888:8888
      - 7860:7860
    command: "start-notebook.sh --ServerApp.token='' --ServerApp.password='' --ServerApp.allow_origin='*' --ServerApp.base_url=/jupyter --ServerApp.allow_remote_access=True"
    environment:
      SHELL: "/bin/bash"
      JUPYTER_ENABLE_LAB: "yes"
    # The service must be connected to the "app-network" Docker network
    networks:
      - app-network
    # SYS_ADMIN and fuse are required to mount workspace resources into the
    # container.
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

volumes:
  work:

networks:
  # The Docker network must be named "app-network". This is an external network
  # that is created outside of this docker-compose file.
  app-network:
    external: true
