[SERVICE]
    Flush 5

[INPUT]
    Name tail
    Tag vm-post-startup-logs
    Path /home/dataproc/.workbench/post-startup-output.txt
    Path_Key filepath
    DB /var/lib/fluent-bit/flb_post_startup.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB

[INPUT]
    Name tail
    Tag vm-boot-logs
    Path /home/dataproc/.workbench/boot-output.txt
    Path_Key filepath
    DB /var/lib/fluent-bit/flb_boot.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB

[INPUT]
    Name tail
    Tag vm-yarn-logs
    Path /var/log/hadoop-yarn/*.log
    Path_Key filepath
    DB /var/lib/fluent-bit/flb_yarn.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB
    Rotate_Wait 30
    Refresh_Interval 10

[INPUT]
    Name tail
    Tag vm-yarn-logs.container.*
    Path /var/log/hadoop-yarn/container/*/*.log
    Path_Key filepath
    DB /var/lib/fluent-bit/flb_yarn-container.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB
    Rotate_Wait 30
    Refresh_Interval 10

[INPUT]
    Name systemd
    Tag vm-journald-startup-logs
    Path /var/log/journal
    Systemd_Filter _SYSTEMD_UNIT=google-startup-scripts.service
    Mem_Buf_Limit 10MB

[INPUT]
    Name systemd
    Tag vm-journald-logs
    Path /var/log/journal
    Systemd_Filter SYSLOG_IDENTIFIER=knox-cert-regen
    Systemd_Filter _SYSTEMD_UNIT=jupyter.service
    Mem_Buf_Limit 10MB

[INPUT]
    Name tail
    Tag vm-docker-logs
    Parser docker
    Path /var/lib/docker/containers/*/*.log
    Path_Key filepath
    DB /var/lib/fluent-bit/flb_docker.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB
    Refresh_Interval 5

[OUTPUT]
    name stackdriver
    match vm-*
    resource gce_instance