[SERVICE]
    Flush 5

[INPUT]
    Name systemd
    Tag vm.journal.startup
    Path /var/log/journal
    Systemd_Filter _SYSTEMD_UNIT=devcontainer.service
    Mem_Buf_Limit 10MB

[INPUT]
    Name systemd
    Tag vm.journal.*
    Path /var/log/journal
    Systemd_Filter _SYSTEMD_UNIT=docker.service
    Systemd_Filter _SYSTEMD_UNIT=idle-shutdown.service
    Systemd_Filter _SYSTEMD_UNIT=proxy-prober.service
    Systemd_Filter _SYSTEMD_UNIT=proxy-readiness.service
    Systemd_Filter _SYSTEMD_UNIT=locksmithd.service
    Systemd_Filter _SYSTEMD_UNIT=update-engine.service
    Mem_Buf_Limit 10MB

[INPUT]
    Name systemd
    Tag vm.journal.stats
    Path /var/log/journal
    Systemd_Filter _SYSTEMD_UNIT=machine-stats-exporter.service
    Mem_Buf_Limit 10MB

[INPUT]
    Name tail
    Tag vm.docker
    Parser docker
    Path /var/lib/docker/containers/*/*.log
    Path_key filepath
    DB /var/lib/fluent-bit/flb_docker.db
    Read_from_Head true
    Skip_Long_Lines On
    Mem_Buf_Limit 10MB
    Refresh_Interval 5

[OUTPUT]
    name stackdriver
    match vm.*
    resource gce_instance
