version: "2.4"
services:
  app:
    container_name: "application-server"
    build:
      context: .
      target: nemo
    user: jupyter
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --LabApp.token=''
networks:
  app-network:
    external: true
