version: "2.4"
services:
  app:
    container_name: "application-server"
    build:
      context: ./OPTIMEyes/flask_server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/workspace:cached
      - work:/config:cached
      - data:/workspace/data:cached
      - ./flask_server:/flask_server
      - ./Image-Comparator-Data:/Image-Comparator-Data 
    working_dir: /flask_server
    env_file:
      - .env
    environment:
      - FLASK_APP=${FLASK_APP}
      - IMAGE_COMPARATOR_DATA=${IMAGE_COMPARATOR_DATA}
      - DNS=${DNS}
      - SSL=${SSL}
      - DB_PORT=${DB_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - DEPLOY=${DEPLOY}
      - COUCH_DB=${COUCH_DB}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - ADMIN_PARTY=${ADMIN_PARTY}
      - SECRET_KEY=${SECRET_KEY}
    command: bash -c "/flask_server/OPTIMEyes/utils/setup.sh"
    # command: sleep 1000000
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - couchdb

  couchdb:
    container_name: "couchdb-server"
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    env_file:
      - .env
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - app-network

  monailabel:
    build:
      context: ./OPTIMEyes/monailabel
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./monailabel:/monailabel
    stdin_open: true
    tty: true
    working_dir: /monailabel
    env_file:
      - .env
    environment:
      - MONAI_LABEL_ENV=development
    command: monailabel start_server --app apps/monaibundle --studies datastore --conf bundles IntegrationBundle,SegformerBundle,MedSamBundle --conf zoo_source ngc
    # command: bash

networks:
  app-network:
    external: true

volumes:
  work:
  data:
  couchdb_data:
  flask_server:
  monailabel:
