version: "2.4"
services:
  app:
    container_name: "flask-api-server"
    build: .
    user: "root"
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    external: false