version: "2.4"
services:
  app:
    container_name: "application-server"
    image: "us-central1-docker.pkg.dev/verily-workbench-public/apps/workbench-jupyter:latest"
    user: "jupyter"
    restart: always
    volumes:
      - .:/workspace:cached
      # Mount docker socket so application can access the docker daemon in the host
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8888"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
