name: Build and Push Firmware to NetRise

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: "Pre-Public Test"
      env:
        value_test: ${{ secrets.NIKSINGH_TEST }}
      run: |
        touch .test
        echo Email="$value_test" >> .test
        cat .test
