name: Build and Push Firmware to NetRise

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: "Pre-Public Test"
      env:
        GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
      run: |
        echo Email="$GCP_SA_EMAIL" >> .test
        cat .test
