version: "2.4"
services:
  app:
    container_name: "application-server"
    # image: "nvcr.io/nvidia/pytorch:24.09-py3"
    image: "pytorch/pytorch:2.5.0-cuda12.4-cudnn9-runtime"
    user: "jupyter"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    restart: always
    volumes:
      - .:/workspace:cached
    ports:
      - "8888:8888"
    command: "/home/jupyter/.local/bin/jupyter lab"
    environment:
      SHELL: "/bin/bash"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
